[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  # Set the Node.js version
  NODE_VERSION = "18"

[functions]
  # This directory is where your server functions will be built
  directory = "netlify/functions"
  
# For server-side rendering, we need to handle all paths
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200