[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  # Set the Node.js version
  NODE_VERSION = "18"
  
# For server-side rendering, we need to handle all paths
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200